import React from 'react';
import { PricingSection } from '../components/landing/PricingSection';
import { Accordion, AccordionItem } from '../components/ui/Accordion';

export function PricingPage() {
  return (
    <div className="min-h-screen bg-zinc-950 py-12">
      <PricingSection />

      {/* FAQ Accordion Section */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-8">
        <div className="text-center space-y-2">
          <h2 className="text-2xl font-bold text-white">Frequently Asked Questions</h2>
          <p className="text-sm text-zinc-400">Everything you need to know about plans, downloads, and webhooks.</p>
        </div>

        <Accordion className="bg-zinc-900/60 p-6 rounded-3xl border border-white/[0.08]">
          <AccordionItem title="Can I download the generated project source code as a .ZIP file?" defaultOpen>
            Yes! When project synthesis finishes, click "Download ZIP" to package the entire file tree into a ready-to-run `.zip` archive containing your package.json, React components, Express backend controllers, and README instructions.
          </AccordionItem>
          <AccordionItem title="How does the n8n Webhook connection work?">
            In the settings modal or command palette (Ctrl+K), you can enter your custom n8n webhook URL. When enabled, your prompt and tech stack parameters are dispatched to your n8n workflow endpoint over HTTP POST.
          </AccordionItem>
          <AccordionItem title="What technologies and frameworks are supported?">
            AuraCraft AI supports React (Vite), Next.js, Vue 3, Angular on the frontend; Express.js, Node.js, NestJS, Python Django, and PHP Laravel on the backend; MongoDB, PostgreSQL, MySQL, Supabase, and Firebase databases.
          </AccordionItem>
          <AccordionItem title="Is the generated code commercial-use friendly?">
            Absolutely! You retain 100% full ownership of all code and architecture generated by AuraCraft AI without any royalty or license restrictions.
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
}
